; IR Mini V105 — 万能红外遥控器（自定义固件）
; AP 直连 + iOS 风格内嵌 WebUI + 空调品牌控制 + 学习功能

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino

; 红外遥控库
lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.6

; 编译优化
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH

; 刷写
upload_speed = 115200
upload_port = COM10
monitor_speed = 115200

; 4MB Flash: 全部给程序（不用文件系统，HTML 内嵌 PROGMEM）
board_build.ldscript = eagle.flash.4m.ld
