; IR Mini V105 — 万能红外遥控器
; AP/STA 双模式 + iOS 风格 WebUI + 空调控制 + 学习 + MQTT + 传感器 + OTA

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino

; 依赖库
lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.6
    knolleary/PubSubClient@^2.8
    milesburton/DallasTemperature@^3.11.0

; 编译优化
build_flags =
    -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -DVTABLES_IN_FLASH
    -DMQTT_MAX_PACKET_SIZE=1024

; 刷写
upload_speed = 115200
upload_port = COM10
monitor_speed = 115200

; 4MB Flash: ~1019KB 程序 + ~1028KB OTA 缓冲 + ~2024KB LittleFS（配置存储）
board_build.ldscript = eagle.flash.4m1m.ld
